site_name: CP-Algorithms
theme:
  name: material
  language: ka
nav:
  - მთავარი: 'index.md'
  - ალგებრა:
    - საფუძვლები:
      - 'ორობითი გაძლიერება': './algebra/binary-exp.md'
      - 'ევკლიდური ალგორითმი უდიდესი საერთო გამყოფის გამოსათვლელად': './algebra/euclid-algorithm.md'
      - 'გაფართოებული ევკლიდეს ალგორითმი': './algebra/extended-euclid-algorithm.md'
      - 'წრფივი დიოფანტინის განტოლებები': './algebra/linear-diophantine-equation.md'
      - 'ფიბონაჩის რიცხვები': './algebra/fibonacci-numbers.md'
extra_javascript:
  - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      # tex_inline_wrap: ["$", "$"]
      tex_block_wrap: ["$$", "$$"]
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - toc:
      permalink: true

# plugins:
#   # - mkdocs-simple-hooks:
#   #     hooks:
#   #       on_env: "hooks:on_env"
#   - literate-nav:
#     nav_file: navigation.md
#   - macros