site_name: CP-Algorithms
theme:
  name: material
  language: ka
nav:
  - მთავარი: 'index.md'
  - ალგებრა:
    - საფუძვლები:
      - 'ორობითი გაძლიერება': './algebra/binary-exp.md'
      - 'ევკლიდური ალგორითმი უდიდესი საერთო გამყოფის გამოსათვლელად': './algebra/euclid-algorithm.md'
      - 'გაფართოებული ეუკლიდეს ალგორითმი': './algebra/extended-euclid-algorithm.md'
      - 'წრფივი დიოფანტინის განტოლებები': './algebra/linear-diophantine-equation.md'
      - 'ფიბონაჩის რიცხვები': './algebra/fibonacci-numbers.md'
    - მარტივი რიცხვები:
      - 'ერატოსთენეს საცერი': './algebra/sieve-of-eratosthenes.md'
      - 'წრფივი საცერი': './algebra/prime-sieve-linear.md'
      - 'პირველობის ტესტები': './algebra/primality_tests.md'
      - 'მთელი რიცხვების ფაქტორიზაცია': './algebra/factorization.md'
    - რიცხვთა თეორიული ფუნქციები:
      - 'ეილერის ტოტიენტის ფუნქცია': './algebra/phi-function.md'
      - 'გამყოფთა რაოდენობა / გამყოფთა ჯამი': './algebra/divisors.md'
  - დინამიური პროგრამირება:
    - 'დინამიური პროგრამირების შესავალი': './dynamic_programming/intro-to-dp.md'
    - დინამიური პროგრამირების ოპტიმიზაციები:
      - 'Divide and Conquer DP': './dynamic_programming/divide-and-conquer-dp.md'
      - 'კნუტის ოპტიმიზაცია': './dynamic_programming/knuth-optimization.md'
    - დავალებები: 
      - 'დინამიური პროგრამირება გატეხილ პროფილზე. პრობლემა "პარკეტი"': './dynamic_programming/profile-dynamics.md'
      - 'ყველაზე დიდი ნულოვანი ქვემატრიცის პოვნა': './dynamic_programming/zero_matrix'

extra_javascript:
  # - javascript/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
      # tex_inline_wrap: ["$", "$"]
      # tex_block_wrap: ["$$", "$$"]
  - pymdownx.highlight
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - toc:
      permalink: true
# plugins:
#   - math
#   # - mkdocs-simple-hooks:
#   #     hooks:
#   #       on_env: "hooks:on_env"
#   - literate-nav:
#     nav_file: navigation.md
#   - macros